fix: json formatting output
keebox/keebox pull request #22
Opened 2021-11-07 22:11 UTC by yoyrandao

2021-11-07 22:12 UTC, yoyrandao commented
Closes #22

2021-11-08 08:39 UTC, TheAsda requested changes

2021-11-08 08:39 UTC, TheAsda commented on src/SecretsService/Services/Formatters/JsonSecretFormatter.cs
> +		public JsonSecretFormatter(ISerializer? serializer)
Nullable?

2021-11-08 08:39 UTC, TheAsda commented on src/SecretsService/Services/Formatters/XmlSecretFormatter.cs
>  		public XmlSecretFormatter(ISerializer? serializer) =>
Body

2021-11-13 17:40 UTC, yoyrandao commented on src/SecretsService/Services/Formatters/JsonSecretFormatter.cs
> +		public JsonSecretFormatter(ISerializer? serializer)
done

2021-11-13 17:40 UTC, yoyrandao commented on src/SecretsService/Services/Formatters/XmlSecretFormatter.cs
>  		public XmlSecretFormatter(ISerializer? serializer) =>
done

2021-11-13 17:58 UTC, TheAsda approved these changes

2021-11-13 18:03 UTC, merged