Add roles
keebox/keebox pull request #25
Opened 2021-11-13 20:09 UTC by TheAsda

2021-11-13 20:44 UTC, yoyrandao requested changes

2021-11-13 20:44 UTC, yoyrandao commented on src/Common/DataAccess/Entities/Group.cs
> +﻿using System;
delete

2021-11-13 20:44 UTC, yoyrandao commented on src/Common/DataAccess/Repositories/Abstractions/IRoleRepository.cs
> +		Guid Create(string name);
Добавь Get

2021-11-13 20:44 UTC, yoyrandao commented on src/Common/DataAccess/Repositories/InMemory/InMemoryRoleRepository.cs
> +				throw new AlreadyExistsException("Role already exists");
Добавить в фильтр

2021-11-13 20:44 UTC, yoyrandao commented on src/Common/Managers/IRoleManager.cs
> +	public interface IRoleManager
Соответственно, GetRole

2021-11-13 20:44 UTC, yoyrandao commented on src/Common.UnitTests/Managers/SecretsManagerTests.cs
> +		private ISecretManager _target;
Заодно перемести вниз

2021-11-13 20:44 UTC, yoyrandao commented on src/SecretsService/Controllers/RoleController.cs
> +	public class RoleController : ControllerBase
Добавить Get

2021-11-13 20:44 UTC, yoyrandao commented on src/SecretsService/Controllers/RoleController.cs
> +		[HttpGet]
Напиши у всех ProducesResponseType итд

2021-11-13 20:44 UTC, yoyrandao commented on src/SecretsService/Controllers/RoleController.cs
> +	[Route("role")]
RouteMap

2021-11-14 11:02 UTC, yoyrandao requested changes

2021-11-14 11:02 UTC, yoyrandao commented on src/Common/DataAccess/Entities/Role.cs
> +		public string Name { get; set; }
init?

2021-11-14 11:02 UTC, yoyrandao commented on src/Common/Managers/RoleManager.cs
> +			if (_roleRepository.Exists(name))
Дублирование кода, вынеси в функцию

2021-11-14 11:02 UTC, yoyrandao commented on src/Common.IntegrationTests/DataAccess/Repositories/Postgres/PostgresRoleRepositoryTests.cs
> +			list.Count(x => x.Name == name).Should().Be(0);
там есть ShouldHaveCount

2021-11-14 11:02 UTC, yoyrandao commented on src/Common.IntegrationTests/DataAccess/Repositories/Postgres/PostgresRoleRepositoryTests.cs
> +			exists.Should().Be(true);
BeTrue

2021-11-14 11:02 UTC, yoyrandao commented on src/Common.IntegrationTests/DataAccess/Repositories/Postgres/PostgresRoleRepositoryTests.cs
> +			exists.Should().Be(true);
ниже везде так же

2021-11-14 20:23 UTC, TheAsda commented on src/Common.IntegrationTests/DataAccess/Repositories/Postgres/PostgresRoleRepositoryTests.cs
> +			list.Count(x => x.Name == name).Should().Be(0);
Он без условия

2021-11-14 20:33 UTC, yoyrandao approved these changes

2021-11-14 20:35 UTC, merged