add rbac authorization, assignment repository
keebox/keebox pull request #32
Opened 2021-12-04 18:08 UTC by yoyrandao

closes #20

2021-12-04 19:59 UTC, TheAsda requested changes
Добавить бы еще группу `admin`

2021-12-04 19:59 UTC, TheAsda commented on src/Common/DataAccess/Repositories/Abstractions/IAssignmentRepository.cs
> +		public IEnumerable<Guid> GetByAccount(Guid accountId);
Какой `public`?

2021-12-04 19:59 UTC, TheAsda commented on src/Common/DataAccess/Repositories/Abstractions/IAssignmentRepository.cs
> +		public void Assign(Guid accountId, Guid roleId);
Какой `public`?

2021-12-04 19:59 UTC, TheAsda commented on src/Common/DataAccess/Repositories/InMemory/InMemoryAssignmentRepository.cs
> +		public IEnumerable<Guid> GetByAccount(Guid accountId)
`Get` обычно возвращает entity

2021-12-04 19:59 UTC, TheAsda commented on src/Common/DataAccess/Repositories/Postgres/PostgresAssignmentRepository.cs
> +			EnsureArg.IsNotDefault(accountId);
Можно не проверять

2021-12-04 19:59 UTC, TheAsda commented on src/SecretsService/Controllers/AccountController.cs
> +					if (payload.Data!.ContainsKey("generate") && payload.Data!["generate"].ToString()!.Equals("true"))
`ToLower`?

2021-12-04 20:52 UTC, yoyrandao commented on src/Common/DataAccess/Repositories/Abstractions/IAssignmentRepository.cs
> +		public IEnumerable<Guid> GetByAccount(Guid accountId);
done

2021-12-04 20:52 UTC, yoyrandao commented on src/Common/DataAccess/Repositories/Abstractions/IAssignmentRepository.cs
> +		public void Assign(Guid accountId, Guid roleId);
done

2021-12-04 20:52 UTC, yoyrandao commented on src/Common/DataAccess/Repositories/InMemory/InMemoryAssignmentRepository.cs
> +		public IEnumerable<Guid> GetByAccount(Guid accountId)
done

2021-12-04 20:52 UTC, yoyrandao commented on src/SecretsService/Controllers/AccountController.cs
> +					if (payload.Data!.ContainsKey("generate") && payload.Data!["generate"].ToString()!.Equals("true"))
done

2021-12-12 09:37 UTC, TheAsda commented on src/Common/DataAccess/Repositories/InMemory/InMemoryAccountRepository.cs
> +			return Storage.Single(x => x.TokenHash != null && x.TokenHash.Equals(tokenHash, StringComparison.OrdinalIgnoreCase));
is not null

2021-12-12 09:39 UTC, TheAsda commented on src/Common/DataAccess/Repositories/Postgres/EntityConfigurations/RoleEntityTableConfiguration.cs
> +				.Property(x => x.Name).HasColumnName(nameof(Role.Name).ToLower())
.HasDataType

2021-12-12 09:39 UTC, TheAsda commented on src/Common/DataAccess/Repositories/Postgres/EntityConfigurations/AccountEntityTableConfiguration.cs
> +				.Property(x => x.Name).HasColumnName(nameof(Account.Name).ToLower())
.HasDataType

2021-12-12 09:41 UTC, TheAsda commented on src/Common/DataAccess/Repositories/Postgres/PostgresAccountRepository.cs
> +				.SingleOrDefault(x => x.Name.Equals(accountName)) is not null;
IgnoreCase?

2021-12-12 09:48 UTC, TheAsda commented on src/Common/Helpers/ITokenService.cs
> +		string GenerateJwtToken(Guid userId, Role[] roles);
Time span?

2021-12-12 09:57 UTC, TheAsda commented on src/Common/Managers/AccountManager.cs
> +		public void CreateTokenAccount(Guid id, string name, string token)
CreateSystemAccount, remove Id

2021-12-12 10:02 UTC, TheAsda commented on src/Common/DataAccess/Repositories/Postgres/Migrations/SystemRolesMigration.cs
> +					{ nameof(Role.Name).ToLower(), Enum.GetName(typeof(SystemRole), SystemRole.Admin)!.ToLower() },
FormattedSystemRole.Admin?

2021-12-12 10:04 UTC, TheAsda commented on src/Common/Managers/IAccountManager.cs
> +		void CreateTokenAccount(Guid id, string name, string token);
```cs
void CreateSystemTokenAccount(Guid id, string name, string token);
void CreateSystemTokenAccount(string name, string token);
void CreateTokenAccount(string name, string token);
```

2021-12-12 10:32 UTC, TheAsda commented on src/SecretsService/Controllers/AccountController.cs
> +			_accountManager.AssignRoleToAccount((Guid)payload.RoleId, (Guid)payload.AccountId);
(Guid)Guid?

2021-12-12 10:32 UTC, TheAsda commented on src/SecretsService/Controllers/AccountController.cs
> +		[ProducesResponseType(StatusCodes.Status200OK)]
201 - Created

2021-12-12 10:36 UTC, TheAsda commented on src/SecretsService/Controllers/PermissionController.cs
> +	[Authenticate] [AuthorizePrivileged]
\n?

2021-12-12 10:40 UTC, TheAsda commented on src/SecretsService/Controllers/RoleController.cs
> +		[AuthorizePrivileged]
Может на весь контроллер?

2021-12-12 10:42 UTC, TheAsda commented on src/SecretsService/Controllers/SecretController.cs
> +	[Authenticate] [AuthorizeForGroup]
\n?

2021-12-12 15:25 UTC, TheAsda requested changes

2021-12-12 15:25 UTC, TheAsda commented on src/SecretsService/Models/EntityCreation/AccountCreationPayload.cs
> +		public string? Name { get; init; }
Not nullable

2021-12-12 19:39 UTC, TheAsda approved these changes

2021-12-12 19:39 UTC, TheAsda commented on src/SecretsService/Controllers/AccountController.cs
> +					if (creationPayload.GenerateToken != null && (bool)creationPayload.GenerateToken)
`.Value`

2021-12-12 19:44 UTC, merged